# Generated by Django 3.2.12 on 2022-02-23 16:56

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, verbose_name='ид')),
                ('first_name', models.CharField(max_length=64, verbose_name='имя')),
                ('last_name', models.CharField(max_length=64, verbose_name='фамилия')),
                ('birthday_year', models.PositiveIntegerField(verbose_name='дата рождения')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='обновлено')),
            ],
        ),
    ]
